// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invoices.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO invoices (
    invoice_number, customer_name, customer_email, customer_phone, total, notes , items , discounts, user_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,$8, $9
) RETURNING id, invoice_number, customer_name, customer_email, customer_phone, total, notes, items, discounts, created_at, updated_at, user_id
`

type CreateInvoiceParams struct {
	InvoiceNumber string
	CustomerName  string
	CustomerEmail string
	CustomerPhone sql.NullString
	Total         string
	Notes         string
	Items         json.RawMessage
	Discounts     json.RawMessage
	UserID        uuid.UUID
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRowContext(ctx, createInvoice,
		arg.InvoiceNumber,
		arg.CustomerName,
		arg.CustomerEmail,
		arg.CustomerPhone,
		arg.Total,
		arg.Notes,
		arg.Items,
		arg.Discounts,
		arg.UserID,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.InvoiceNumber,
		&i.CustomerName,
		&i.CustomerEmail,
		&i.CustomerPhone,
		&i.Total,
		&i.Notes,
		&i.Items,
		&i.Discounts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const deleteInvoice = `-- name: DeleteInvoice :exec
DELETE FROM invoices WHERE id = $1
`

func (q *Queries) DeleteInvoice(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteInvoice, id)
	return err
}

const getInvoice = `-- name: GetInvoice :one
SELECT id, invoice_number, customer_name, customer_email, customer_phone, total, notes, items, discounts, created_at, updated_at, user_id FROM invoices WHERE id = $1
`

func (q *Queries) GetInvoice(ctx context.Context, id uuid.UUID) (Invoice, error) {
	row := q.db.QueryRowContext(ctx, getInvoice, id)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.InvoiceNumber,
		&i.CustomerName,
		&i.CustomerEmail,
		&i.CustomerPhone,
		&i.Total,
		&i.Notes,
		&i.Items,
		&i.Discounts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const getInvoiceByNumber = `-- name: GetInvoiceByNumber :one
SELECT id, invoice_number, customer_name, customer_email, customer_phone, total, notes, items, discounts, created_at, updated_at, user_id FROM invoices WHERE invoice_number = $1
`

func (q *Queries) GetInvoiceByNumber(ctx context.Context, invoiceNumber string) (Invoice, error) {
	row := q.db.QueryRowContext(ctx, getInvoiceByNumber, invoiceNumber)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.InvoiceNumber,
		&i.CustomerName,
		&i.CustomerEmail,
		&i.CustomerPhone,
		&i.Total,
		&i.Notes,
		&i.Items,
		&i.Discounts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const getUserInvoices = `-- name: GetUserInvoices :many
SELECT id, invoice_number, customer_name, customer_email, customer_phone, total, notes, items, discounts, created_at, updated_at, user_id FROM invoices WHERE user_id = $1
ORDER BY created_at DESC 
LIMIT $2
OFFSET $3
`

type GetUserInvoicesParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) GetUserInvoices(ctx context.Context, arg GetUserInvoicesParams) ([]Invoice, error) {
	rows, err := q.db.QueryContext(ctx, getUserInvoices, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invoice
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceNumber,
			&i.CustomerName,
			&i.CustomerEmail,
			&i.CustomerPhone,
			&i.Total,
			&i.Notes,
			&i.Items,
			&i.Discounts,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoices = `-- name: ListInvoices :many
SELECT id, invoice_number, customer_name, customer_email, customer_phone, total, notes, items, discounts, created_at, updated_at, user_id FROM invoices ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListInvoicesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListInvoices(ctx context.Context, arg ListInvoicesParams) ([]Invoice, error) {
	rows, err := q.db.QueryContext(ctx, listInvoices, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invoice
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceNumber,
			&i.CustomerName,
			&i.CustomerEmail,
			&i.CustomerPhone,
			&i.Total,
			&i.Notes,
			&i.Items,
			&i.Discounts,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvoice = `-- name: UpdateInvoice :one
UPDATE invoices SET
    customer_name = $2,
    customer_email = $3,
    customer_phone = $4,
    total = $5,
    notes = $6,
    items =$7,
    discounts=$8,
    updated_at = NOW()
WHERE id = $1 RETURNING id, invoice_number, customer_name, customer_email, customer_phone, total, notes, items, discounts, created_at, updated_at, user_id
`

type UpdateInvoiceParams struct {
	ID            uuid.UUID
	CustomerName  string
	CustomerEmail string
	CustomerPhone sql.NullString
	Total         string
	Notes         string
	Items         json.RawMessage
	Discounts     json.RawMessage
}

func (q *Queries) UpdateInvoice(ctx context.Context, arg UpdateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRowContext(ctx, updateInvoice,
		arg.ID,
		arg.CustomerName,
		arg.CustomerEmail,
		arg.CustomerPhone,
		arg.Total,
		arg.Notes,
		arg.Items,
		arg.Discounts,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.InvoiceNumber,
		&i.CustomerName,
		&i.CustomerEmail,
		&i.CustomerPhone,
		&i.Total,
		&i.Notes,
		&i.Items,
		&i.Discounts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}
