// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invoices.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const countCustomersInvoices = `-- name: CountCustomersInvoices :one
SELECT COUNT(*) FROM invoices WHERE customer_email=$1
`

func (q *Queries) CountCustomersInvoices(ctx context.Context, customerEmail string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCustomersInvoices, customerEmail)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countInvoices = `-- name: CountInvoices :one

SELECT COUNT(*) FROM invoices
`

// -- name: DeleteInvoice :exec
// DELETE FROM invoices WHERE id = $1;
func (q *Queries) CountInvoices(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countInvoices)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWorkersCreatedInvoices = `-- name: CountWorkersCreatedInvoices :one
SELECT COUNT(*) FROM invoices WHERE user_id=$1
`

func (q *Queries) CountWorkersCreatedInvoices(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWorkersCreatedInvoices, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO invoices (
    invoice_number, customer_name, customer_email, customer_phone, total, notes , items , discounts, user_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,$8,$9
) RETURNING id, invoice_number, customer_name, customer_email, customer_phone, total, notes, items, discounts, created_at, updated_at, user_id, status, quote_id, deleted_at
`

type CreateInvoiceParams struct {
	InvoiceNumber string
	CustomerName  string
	CustomerEmail string
	CustomerPhone sql.NullString
	Total         string
	Notes         string
	Items         json.RawMessage
	Discounts     json.RawMessage
	UserID        uuid.UUID
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRowContext(ctx, createInvoice,
		arg.InvoiceNumber,
		arg.CustomerName,
		arg.CustomerEmail,
		arg.CustomerPhone,
		arg.Total,
		arg.Notes,
		arg.Items,
		arg.Discounts,
		arg.UserID,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.InvoiceNumber,
		&i.CustomerName,
		&i.CustomerEmail,
		&i.CustomerPhone,
		&i.Total,
		&i.Notes,
		&i.Items,
		&i.Discounts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Status,
		&i.QuoteID,
		&i.DeletedAt,
	)
	return i, err
}

const createInvoiceWithQuote = `-- name: CreateInvoiceWithQuote :one
INSERT INTO invoices (
    invoice_number, customer_name, customer_email, customer_phone, total, notes , items , discounts, user_id,quote_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,$8,$9,$10
) RETURNING id, invoice_number, customer_name, customer_email, customer_phone, total, notes, items, discounts, created_at, updated_at, user_id, status, quote_id, deleted_at
`

type CreateInvoiceWithQuoteParams struct {
	InvoiceNumber string
	CustomerName  string
	CustomerEmail string
	CustomerPhone sql.NullString
	Total         string
	Notes         string
	Items         json.RawMessage
	Discounts     json.RawMessage
	UserID        uuid.UUID
	QuoteID       uuid.NullUUID
}

func (q *Queries) CreateInvoiceWithQuote(ctx context.Context, arg CreateInvoiceWithQuoteParams) (Invoice, error) {
	row := q.db.QueryRowContext(ctx, createInvoiceWithQuote,
		arg.InvoiceNumber,
		arg.CustomerName,
		arg.CustomerEmail,
		arg.CustomerPhone,
		arg.Total,
		arg.Notes,
		arg.Items,
		arg.Discounts,
		arg.UserID,
		arg.QuoteID,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.InvoiceNumber,
		&i.CustomerName,
		&i.CustomerEmail,
		&i.CustomerPhone,
		&i.Total,
		&i.Notes,
		&i.Items,
		&i.Discounts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Status,
		&i.QuoteID,
		&i.DeletedAt,
	)
	return i, err
}

const getCustomerInvoices = `-- name: GetCustomerInvoices :many
SELECT id, invoice_number, customer_name, customer_email, customer_phone, total, notes, items, discounts, created_at, updated_at, user_id, status, quote_id, deleted_at FROM invoices WHERE customer_email = $1
AND deleted_at IS NULL
ORDER BY created_at DESC 
LIMIT $2
OFFSET $3
`

type GetCustomerInvoicesParams struct {
	CustomerEmail string
	Limit         int32
	Offset        int32
}

func (q *Queries) GetCustomerInvoices(ctx context.Context, arg GetCustomerInvoicesParams) ([]Invoice, error) {
	rows, err := q.db.QueryContext(ctx, getCustomerInvoices, arg.CustomerEmail, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invoice
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceNumber,
			&i.CustomerName,
			&i.CustomerEmail,
			&i.CustomerPhone,
			&i.Total,
			&i.Notes,
			&i.Items,
			&i.Discounts,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.Status,
			&i.QuoteID,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInvoice = `-- name: GetInvoice :one
SELECT id, invoice_number, customer_name, customer_email, customer_phone, total, notes, items, discounts, created_at, updated_at, user_id, status, quote_id, deleted_at FROM invoices WHERE id = $1
`

func (q *Queries) GetInvoice(ctx context.Context, id uuid.UUID) (Invoice, error) {
	row := q.db.QueryRowContext(ctx, getInvoice, id)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.InvoiceNumber,
		&i.CustomerName,
		&i.CustomerEmail,
		&i.CustomerPhone,
		&i.Total,
		&i.Notes,
		&i.Items,
		&i.Discounts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Status,
		&i.QuoteID,
		&i.DeletedAt,
	)
	return i, err
}

const getInvoiceByNumber = `-- name: GetInvoiceByNumber :one
SELECT id, invoice_number, customer_name, customer_email, customer_phone, total, notes, items, discounts, created_at, updated_at, user_id, status, quote_id, deleted_at FROM invoices WHERE invoice_number = $1
`

func (q *Queries) GetInvoiceByNumber(ctx context.Context, invoiceNumber string) (Invoice, error) {
	row := q.db.QueryRowContext(ctx, getInvoiceByNumber, invoiceNumber)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.InvoiceNumber,
		&i.CustomerName,
		&i.CustomerEmail,
		&i.CustomerPhone,
		&i.Total,
		&i.Notes,
		&i.Items,
		&i.Discounts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Status,
		&i.QuoteID,
		&i.DeletedAt,
	)
	return i, err
}

const getWorkersCreatedInvoices = `-- name: GetWorkersCreatedInvoices :many
SELECT id, invoice_number, customer_name, customer_email, customer_phone, total, notes, items, discounts, created_at, updated_at, user_id, status, quote_id, deleted_at FROM invoices WHERE user_id = $1
ORDER BY created_at DESC 
LIMIT $2
OFFSET $3
`

type GetWorkersCreatedInvoicesParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) GetWorkersCreatedInvoices(ctx context.Context, arg GetWorkersCreatedInvoicesParams) ([]Invoice, error) {
	rows, err := q.db.QueryContext(ctx, getWorkersCreatedInvoices, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invoice
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceNumber,
			&i.CustomerName,
			&i.CustomerEmail,
			&i.CustomerPhone,
			&i.Total,
			&i.Notes,
			&i.Items,
			&i.Discounts,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.Status,
			&i.QuoteID,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoices = `-- name: ListInvoices :many
SELECT id, invoice_number, customer_name, customer_email, customer_phone, total, notes, items, discounts, created_at, updated_at, user_id, status, quote_id, deleted_at FROM invoices ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListInvoicesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListInvoices(ctx context.Context, arg ListInvoicesParams) ([]Invoice, error) {
	rows, err := q.db.QueryContext(ctx, listInvoices, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invoice
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceNumber,
			&i.CustomerName,
			&i.CustomerEmail,
			&i.CustomerPhone,
			&i.Total,
			&i.Notes,
			&i.Items,
			&i.Discounts,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.Status,
			&i.QuoteID,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInvoiceAsPaid = `-- name: MarkInvoiceAsPaid :exec
UPDATE invoices 
SET status = 'paid', updated_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkInvoiceAsPaid(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markInvoiceAsPaid, id)
	return err
}

const softDeleteInvoice = `-- name: SoftDeleteInvoice :exec
UPDATE invoices 
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND customer_email = $2
`

type SoftDeleteInvoiceParams struct {
	ID            uuid.UUID
	CustomerEmail string
}

func (q *Queries) SoftDeleteInvoice(ctx context.Context, arg SoftDeleteInvoiceParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteInvoice, arg.ID, arg.CustomerEmail)
	return err
}

const updateInvoice = `-- name: UpdateInvoice :one
UPDATE invoices SET
    customer_name = $2,
    customer_email = $3,
    customer_phone = $4,
    total = $5,
    notes = $6,
    items =$7,
    discounts=$8,
    updated_at = NOW()
WHERE id = $1 RETURNING id, invoice_number, customer_name, customer_email, customer_phone, total, notes, items, discounts, created_at, updated_at, user_id, status, quote_id, deleted_at
`

type UpdateInvoiceParams struct {
	ID            uuid.UUID
	CustomerName  string
	CustomerEmail string
	CustomerPhone sql.NullString
	Total         string
	Notes         string
	Items         json.RawMessage
	Discounts     json.RawMessage
}

func (q *Queries) UpdateInvoice(ctx context.Context, arg UpdateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRowContext(ctx, updateInvoice,
		arg.ID,
		arg.CustomerName,
		arg.CustomerEmail,
		arg.CustomerPhone,
		arg.Total,
		arg.Notes,
		arg.Items,
		arg.Discounts,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.InvoiceNumber,
		&i.CustomerName,
		&i.CustomerEmail,
		&i.CustomerPhone,
		&i.Total,
		&i.Notes,
		&i.Items,
		&i.Discounts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Status,
		&i.QuoteID,
		&i.DeletedAt,
	)
	return i, err
}
