// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invoices.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO invoices (
    invoice_number, customer_name, customer_email, customer_phone, discount, total, notes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, invoice_number, customer_name, customer_email, customer_phone, discount, total, notes, created_at, updated_at
`

type CreateInvoiceParams struct {
	InvoiceNumber string
	CustomerName  string
	CustomerEmail string
	CustomerPhone sql.NullString
	Discount      sql.NullString
	Total         string
	Notes         sql.NullString
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRowContext(ctx, createInvoice,
		arg.InvoiceNumber,
		arg.CustomerName,
		arg.CustomerEmail,
		arg.CustomerPhone,
		arg.Discount,
		arg.Total,
		arg.Notes,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.InvoiceNumber,
		&i.CustomerName,
		&i.CustomerEmail,
		&i.CustomerPhone,
		&i.Discount,
		&i.Total,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createItem = `-- name: CreateItem :one
INSERT INTO items (
    invoice_id, name, quantity, price
) VALUES (
    $1, $2, $3, $4
) RETURNING id, invoice_id, name, quantity, price, created_at
`

type CreateItemParams struct {
	InvoiceID uuid.NullUUID
	Name      string
	Quantity  int32
	Price     string
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, createItem,
		arg.InvoiceID,
		arg.Name,
		arg.Quantity,
		arg.Price,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.Name,
		&i.Quantity,
		&i.Price,
		&i.CreatedAt,
	)
	return i, err
}

const deleteInvoice = `-- name: DeleteInvoice :exec
DELETE FROM invoices WHERE id = $1
`

func (q *Queries) DeleteInvoice(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteInvoice, id)
	return err
}

const getInvoiceByID = `-- name: GetInvoiceByID :one
SELECT id, invoice_number, customer_name, customer_email, customer_phone, discount, total, notes, created_at, updated_at FROM invoices WHERE id = $1
`

func (q *Queries) GetInvoiceByID(ctx context.Context, id uuid.UUID) (Invoice, error) {
	row := q.db.QueryRowContext(ctx, getInvoiceByID, id)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.InvoiceNumber,
		&i.CustomerName,
		&i.CustomerEmail,
		&i.CustomerPhone,
		&i.Discount,
		&i.Total,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvoiceByNumber = `-- name: GetInvoiceByNumber :one
SELECT id, invoice_number, customer_name, customer_email, customer_phone, discount, total, notes, created_at, updated_at FROM invoices WHERE invoice_number = $1
`

func (q *Queries) GetInvoiceByNumber(ctx context.Context, invoiceNumber string) (Invoice, error) {
	row := q.db.QueryRowContext(ctx, getInvoiceByNumber, invoiceNumber)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.InvoiceNumber,
		&i.CustomerName,
		&i.CustomerEmail,
		&i.CustomerPhone,
		&i.Discount,
		&i.Total,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getItemsByInvoiceID = `-- name: GetItemsByInvoiceID :many
SELECT id, invoice_id, name, quantity, price, created_at FROM items WHERE invoice_id = $1
`

func (q *Queries) GetItemsByInvoiceID(ctx context.Context, invoiceID uuid.NullUUID) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, getItemsByInvoiceID, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.Name,
			&i.Quantity,
			&i.Price,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoices = `-- name: ListInvoices :many
SELECT id, invoice_number, customer_name, customer_email, customer_phone, discount, total, notes, created_at, updated_at FROM invoices ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListInvoicesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListInvoices(ctx context.Context, arg ListInvoicesParams) ([]Invoice, error) {
	rows, err := q.db.QueryContext(ctx, listInvoices, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invoice
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceNumber,
			&i.CustomerName,
			&i.CustomerEmail,
			&i.CustomerPhone,
			&i.Discount,
			&i.Total,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvoice = `-- name: UpdateInvoice :one
UPDATE invoices SET
    customer_name = $2,
    customer_email = $3,
    customer_phone = $4,
    discount = $5,
    total = $6,
    notes = $7,
    updated_at = NOW()
WHERE id = $1 RETURNING id, invoice_number, customer_name, customer_email, customer_phone, discount, total, notes, created_at, updated_at
`

type UpdateInvoiceParams struct {
	ID            uuid.UUID
	CustomerName  string
	CustomerEmail string
	CustomerPhone sql.NullString
	Discount      sql.NullString
	Total         string
	Notes         sql.NullString
}

func (q *Queries) UpdateInvoice(ctx context.Context, arg UpdateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRowContext(ctx, updateInvoice,
		arg.ID,
		arg.CustomerName,
		arg.CustomerEmail,
		arg.CustomerPhone,
		arg.Discount,
		arg.Total,
		arg.Notes,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.InvoiceNumber,
		&i.CustomerName,
		&i.CustomerEmail,
		&i.CustomerPhone,
		&i.Discount,
		&i.Total,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
