// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Invoice struct {
	ID            uuid.UUID
	InvoiceNumber string
	CustomerName  string
	CustomerEmail string
	CustomerPhone sql.NullString
	Total         string
	Notes         string
	Items         json.RawMessage
	Discounts     json.RawMessage
	CreatedAt     time.Time
	UpdatedAt     time.Time
	UserID        uuid.UUID
}

type RefreshToken struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Token      string
	Revoked    bool
	ReplacedBy uuid.NullUUID
	ExpiresAt  time.Time
	CreatedAt  time.Time
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	FirstName    string
	LastName     string
	PhoneNumber  sql.NullString
	Address      string
	Country      string
	State        string
	Role         string
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}
