// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payments.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
    invoice_id, amount, reference, status
) VALUES (
    $1, $2, $3, $4
) RETURNING id, invoice_id, provider, status, reference, created_at, updated_at, amount, currency, external_id, metadata
`

type CreatePaymentParams struct {
	InvoiceID uuid.UUID
	Amount    string
	Reference string
	Status    PaymentStatus
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, createPayment,
		arg.InvoiceID,
		arg.Amount,
		arg.Reference,
		arg.Status,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.Provider,
		&i.Status,
		&i.Reference,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Amount,
		&i.Currency,
		&i.ExternalID,
		&i.Metadata,
	)
	return i, err
}

const getLatestPendingPayment = `-- name: GetLatestPendingPayment :one
SELECT id, invoice_id, provider, status, reference, created_at, updated_at, amount, currency, external_id, metadata FROM payments
WHERE invoice_id = $1 
  AND status = 'pending'
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestPendingPayment(ctx context.Context, invoiceID uuid.UUID) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getLatestPendingPayment, invoiceID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.Provider,
		&i.Status,
		&i.Reference,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Amount,
		&i.Currency,
		&i.ExternalID,
		&i.Metadata,
	)
	return i, err
}

const getPaymentByReference = `-- name: GetPaymentByReference :one
SELECT id, invoice_id, provider, status, reference, created_at, updated_at, amount, currency, external_id, metadata FROM payments WHERE reference = $1
`

func (q *Queries) GetPaymentByReference(ctx context.Context, reference string) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByReference, reference)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.Provider,
		&i.Status,
		&i.Reference,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Amount,
		&i.Currency,
		&i.ExternalID,
		&i.Metadata,
	)
	return i, err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :exec
UPDATE payments SET
    status = $2,
    external_id = $3
WHERE reference = $1
`

type UpdatePaymentStatusParams struct {
	Reference  string
	Status     PaymentStatus
	ExternalID sql.NullString
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updatePaymentStatus, arg.Reference, arg.Status, arg.ExternalID)
	return err
}
