// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: promos.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const countActivePromos = `-- name: CountActivePromos :one
SELECT COUNT(*) FROM promotions WHERE is_active = true
`

func (q *Queries) CountActivePromos(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActivePromos)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPromos = `-- name: CountPromos :one
SELECT COUNT(*) FROM promotions
`

func (q *Queries) CountPromos(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPromos)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPromotion = `-- name: CreatePromotion :one
INSERT INTO promotions (
    code,
    name,
    description,
    breakdown,
    is_active,
    starts_at,
    expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, code, name, description, breakdown, is_active, starts_at, expires_at, created_at
`

type CreatePromotionParams struct {
	Code        string
	Name        string
	Description sql.NullString
	Breakdown   json.RawMessage
	IsActive    sql.NullBool
	StartsAt    sql.NullTime
	ExpiresAt   sql.NullTime
}

func (q *Queries) CreatePromotion(ctx context.Context, arg CreatePromotionParams) (Promotion, error) {
	row := q.db.QueryRowContext(ctx, createPromotion,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.Breakdown,
		arg.IsActive,
		arg.StartsAt,
		arg.ExpiresAt,
	)
	var i Promotion
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Breakdown,
		&i.IsActive,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActivePromoByCode = `-- name: GetActivePromoByCode :one
SELECT id, code, name, description, breakdown, is_active, starts_at, expires_at, created_at FROM promotions 
WHERE code = $1 
  AND is_active = true 
  AND (expires_at IS NULL OR expires_at > NOW())
LIMIT 1
`

func (q *Queries) GetActivePromoByCode(ctx context.Context, code string) (Promotion, error) {
	row := q.db.QueryRowContext(ctx, getActivePromoByCode, code)
	var i Promotion
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Breakdown,
		&i.IsActive,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActivePromos = `-- name: GetActivePromos :many
SELECT id, code, name, description, breakdown, is_active, starts_at, expires_at, created_at FROM promotions 
WHERE is_active = true
ORDER BY 
    created_at DESC
LIMIT $1 OFFSET $2
`

type GetActivePromosParams struct {
	Limit  int32
	Offset int32
}

// Used for the landing page
func (q *Queries) GetActivePromos(ctx context.Context, arg GetActivePromosParams) ([]Promotion, error) {
	rows, err := q.db.QueryContext(ctx, getActivePromos, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Promotion
	for rows.Next() {
		var i Promotion
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.Breakdown,
			&i.IsActive,
			&i.StartsAt,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPromotionByID = `-- name: GetPromotionByID :one
SELECT id, code, name, description, breakdown, is_active, starts_at, expires_at, created_at FROM promotions WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPromotionByID(ctx context.Context, id uuid.UUID) (Promotion, error) {
	row := q.db.QueryRowContext(ctx, getPromotionByID, id)
	var i Promotion
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Breakdown,
		&i.IsActive,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listActivePromotions = `-- name: ListActivePromotions :many
SELECT id, code, name, description, breakdown, is_active, starts_at, expires_at, created_at FROM promotions 
WHERE is_active = true 
ORDER BY created_at DESC
`

func (q *Queries) ListActivePromotions(ctx context.Context) ([]Promotion, error) {
	rows, err := q.db.QueryContext(ctx, listActivePromotions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Promotion
	for rows.Next() {
		var i Promotion
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.Breakdown,
			&i.IsActive,
			&i.StartsAt,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPromos = `-- name: ListPromos :many
SELECT id, code, name, description, breakdown, is_active, starts_at, expires_at, created_at FROM promotions ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListPromosParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListPromos(ctx context.Context, arg ListPromosParams) ([]Promotion, error) {
	rows, err := q.db.QueryContext(ctx, listPromos, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Promotion
	for rows.Next() {
		var i Promotion
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.Breakdown,
			&i.IsActive,
			&i.StartsAt,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateServicePromo = `-- name: UpdateServicePromo :exec
UPDATE services SET active_promo_ids = $2 WHERE id = $1
`

type UpdateServicePromoParams struct {
	ID             uuid.UUID
	ActivePromoIds []string
}

func (q *Queries) UpdateServicePromo(ctx context.Context, arg UpdateServicePromoParams) error {
	_, err := q.db.ExecContext(ctx, updateServicePromo, arg.ID, pq.Array(arg.ActivePromoIds))
	return err
}
