// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: quote_reqs.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const countQuoteRequests = `-- name: CountQuoteRequests :one
SELECT COUNT(*) FROM quote_requests
`

func (q *Queries) CountQuoteRequests(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countQuoteRequests)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserQuoteRequests = `-- name: CountUserQuoteRequests :one
SELECT COUNT(*) FROM quote_requests WHERE user_id=$1
`

func (q *Queries) CountUserQuoteRequests(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserQuoteRequests, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createQuoteRequest = `-- name: CreateQuoteRequest :one
INSERT INTO quote_requests (user_id, service_id,service_name,  description, attachments, promo_ids, vn_r2_key)
VALUES ($1, $2, $3, $4,$5, $6, $7)
RETURNING id, user_id, service_id, service_name, description, attachments, status, created_at, updated_at, budget, promo_ids, vn_r2_key
`

type CreateQuoteRequestParams struct {
	UserID      uuid.UUID
	ServiceID   uuid.UUID
	ServiceName string
	Description string
	Attachments []string
	PromoIds    []string
	VnR2Key     string
}

func (q *Queries) CreateQuoteRequest(ctx context.Context, arg CreateQuoteRequestParams) (QuoteRequest, error) {
	row := q.db.QueryRowContext(ctx, createQuoteRequest,
		arg.UserID,
		arg.ServiceID,
		arg.ServiceName,
		arg.Description,
		pq.Array(arg.Attachments),
		pq.Array(arg.PromoIds),
		arg.VnR2Key,
	)
	var i QuoteRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServiceID,
		&i.ServiceName,
		&i.Description,
		pq.Array(&i.Attachments),
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Budget,
		pq.Array(&i.PromoIds),
		&i.VnR2Key,
	)
	return i, err
}

const getQuoteRequest = `-- name: GetQuoteRequest :one
SELECT id, user_id, service_id, service_name, description, attachments, status, created_at, updated_at, budget, promo_ids, vn_r2_key FROM quote_requests
WHERE id=$1
`

func (q *Queries) GetQuoteRequest(ctx context.Context, id uuid.UUID) (QuoteRequest, error) {
	row := q.db.QueryRowContext(ctx, getQuoteRequest, id)
	var i QuoteRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServiceID,
		&i.ServiceName,
		&i.Description,
		pq.Array(&i.Attachments),
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Budget,
		pq.Array(&i.PromoIds),
		&i.VnR2Key,
	)
	return i, err
}

const getQuoteRequests = `-- name: GetQuoteRequests :many
SELECT 
    qr.id, qr.user_id, qr.service_id, qr.service_name, qr.description, qr.attachments, qr.status, qr.created_at, qr.updated_at, qr.budget, qr.promo_ids, qr.vn_r2_key, 
    u.email as user_email, 
    u.first_name as user_name,
    s.name as service_name
    
FROM quote_requests qr
JOIN users u ON qr.user_id = u.id
JOIN services s ON qr.service_id = s.id
ORDER BY qr.created_at DESC
LIMIT $1 OFFSET $2
`

type GetQuoteRequestsParams struct {
	Limit  int32
	Offset int32
}

type GetQuoteRequestsRow struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	ServiceID     uuid.UUID
	ServiceName   string
	Description   string
	Attachments   []string
	Status        QuoteRequestStatus
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Budget        sql.NullString
	PromoIds      []string
	VnR2Key       string
	UserEmail     string
	UserName      string
	ServiceName_2 string
}

func (q *Queries) GetQuoteRequests(ctx context.Context, arg GetQuoteRequestsParams) ([]GetQuoteRequestsRow, error) {
	rows, err := q.db.QueryContext(ctx, getQuoteRequests, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetQuoteRequestsRow
	for rows.Next() {
		var i GetQuoteRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ServiceID,
			&i.ServiceName,
			&i.Description,
			pq.Array(&i.Attachments),
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Budget,
			pq.Array(&i.PromoIds),
			&i.VnR2Key,
			&i.UserEmail,
			&i.UserName,
			&i.ServiceName_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserQuoteRequests = `-- name: GetUserQuoteRequests :many
SELECT 
  qr.id, qr.user_id, qr.service_id, qr.service_name, qr.description, qr.attachments, qr.status, qr.created_at, qr.updated_at, qr.budget, qr.promo_ids, qr.vn_r2_key,
  s.name AS service_name,
  q.id AS quote_id
FROM quote_requests qr
JOIN services s ON qr.service_id = s.id
LEFT JOIN quotes q ON q.quote_request_id = qr.id 
WHERE qr.user_id = $1
ORDER BY qr.created_at DESC
LIMIT $2 OFFSET $3
`

type GetUserQuoteRequestsParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

type GetUserQuoteRequestsRow struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	ServiceID     uuid.UUID
	ServiceName   string
	Description   string
	Attachments   []string
	Status        QuoteRequestStatus
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Budget        sql.NullString
	PromoIds      []string
	VnR2Key       string
	ServiceName_2 string
	QuoteID       uuid.NullUUID
}

// Use LEFT JOIN so requests without quotes still show up
func (q *Queries) GetUserQuoteRequests(ctx context.Context, arg GetUserQuoteRequestsParams) ([]GetUserQuoteRequestsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserQuoteRequests, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserQuoteRequestsRow
	for rows.Next() {
		var i GetUserQuoteRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ServiceID,
			&i.ServiceName,
			&i.Description,
			pq.Array(&i.Attachments),
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Budget,
			pq.Array(&i.PromoIds),
			&i.VnR2Key,
			&i.ServiceName_2,
			&i.QuoteID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQuoteRequestDescription = `-- name: UpdateQuoteRequestDescription :exec
UPDATE quote_requests SET description = $2, updated_at = NOW() WHERE id = $1
`

type UpdateQuoteRequestDescriptionParams struct {
	ID          uuid.UUID
	Description string
}

func (q *Queries) UpdateQuoteRequestDescription(ctx context.Context, arg UpdateQuoteRequestDescriptionParams) error {
	_, err := q.db.ExecContext(ctx, updateQuoteRequestDescription, arg.ID, arg.Description)
	return err
}

const updateQuoteRequestStatus = `-- name: UpdateQuoteRequestStatus :exec
UPDATE quote_requests SET status = $2, updated_at = NOW() WHERE id = $1
`

type UpdateQuoteRequestStatusParams struct {
	ID     uuid.UUID
	Status QuoteRequestStatus
}

func (q *Queries) UpdateQuoteRequestStatus(ctx context.Context, arg UpdateQuoteRequestStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateQuoteRequestStatus, arg.ID, arg.Status)
	return err
}
