// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: quotes.sql

package database

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const countQuotes = `-- name: CountQuotes :one
SELECT COUNT(*) FROM quotes
`

func (q *Queries) CountQuotes(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countQuotes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserQuotes = `-- name: CountUserQuotes :one
SELECT COUNT(q.id)
FROM quotes q
JOIN quote_requests qr ON q.quote_request_id = qr.id
WHERE qr.user_id = $1
`

func (q *Queries) CountUserQuotes(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserQuotes, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createQuote = `-- name: CreateQuote :one
INSERT INTO quotes (quote_request_id, amount, breakdown, notes, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, quote_request_id, amount, breakdown, notes, status, expires_at, created_at, updated_at
`

type CreateQuoteParams struct {
	QuoteRequestID uuid.UUID
	Amount         string
	Breakdown      json.RawMessage
	Notes          string
	ExpiresAt      time.Time
}

func (q *Queries) CreateQuote(ctx context.Context, arg CreateQuoteParams) (Quote, error) {
	row := q.db.QueryRowContext(ctx, createQuote,
		arg.QuoteRequestID,
		arg.Amount,
		arg.Breakdown,
		arg.Notes,
		arg.ExpiresAt,
	)
	var i Quote
	err := row.Scan(
		&i.ID,
		&i.QuoteRequestID,
		&i.Amount,
		&i.Breakdown,
		&i.Notes,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQuotes = `-- name: GetQuotes :many
SELECT    q.id, q.quote_request_id, q.amount, q.breakdown, q.notes, q.status, q.expires_at, q.created_at, q.updated_at, 
    s.name as service_name,
    s.icon as service_icon
FROM quotes q 
JOIN quote_requests qr ON q.quote_request_id = qr.id
JOIN services s ON qr.service_id = s.id
LIMIT $1 OFFSET $2
`

type GetQuotesParams struct {
	Limit  int32
	Offset int32
}

type GetQuotesRow struct {
	ID             uuid.UUID
	QuoteRequestID uuid.UUID
	Amount         string
	Breakdown      json.RawMessage
	Notes          string
	Status         QuoteStatus
	ExpiresAt      time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
	ServiceName    string
	ServiceIcon    string
}

func (q *Queries) GetQuotes(ctx context.Context, arg GetQuotesParams) ([]GetQuotesRow, error) {
	rows, err := q.db.QueryContext(ctx, getQuotes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetQuotesRow
	for rows.Next() {
		var i GetQuotesRow
		if err := rows.Scan(
			&i.ID,
			&i.QuoteRequestID,
			&i.Amount,
			&i.Breakdown,
			&i.Notes,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ServiceName,
			&i.ServiceIcon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserQuoteWithService = `-- name: GetUserQuoteWithService :one
SELECT 
    q.id, q.quote_request_id, q.amount, q.breakdown, q.notes, q.status, q.expires_at, q.created_at, q.updated_at, 
    s.name as service_name,
    s.icon as service_icon,
    s.id as service_id
FROM quotes q 
JOIN quote_requests qr ON q.quote_request_id = qr.id
JOIN services s ON qr.service_id = s.id
WHERE qr.user_id = $1 AND q.id= $2
`

type GetUserQuoteWithServiceParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

type GetUserQuoteWithServiceRow struct {
	ID             uuid.UUID
	QuoteRequestID uuid.UUID
	Amount         string
	Breakdown      json.RawMessage
	Notes          string
	Status         QuoteStatus
	ExpiresAt      time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
	ServiceName    string
	ServiceIcon    string
	ServiceID      uuid.UUID
}

func (q *Queries) GetUserQuoteWithService(ctx context.Context, arg GetUserQuoteWithServiceParams) (GetUserQuoteWithServiceRow, error) {
	row := q.db.QueryRowContext(ctx, getUserQuoteWithService, arg.UserID, arg.ID)
	var i GetUserQuoteWithServiceRow
	err := row.Scan(
		&i.ID,
		&i.QuoteRequestID,
		&i.Amount,
		&i.Breakdown,
		&i.Notes,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ServiceName,
		&i.ServiceIcon,
		&i.ServiceID,
	)
	return i, err
}

const getUserQuotesWithService = `-- name: GetUserQuotesWithService :many
SELECT 
    q.id, q.quote_request_id, q.amount, q.breakdown, q.notes, q.status, q.expires_at, q.created_at, q.updated_at, 
    s.name as service_name,
    s.icon as service_icon,
        s.id as service_id

FROM quotes q 
JOIN quote_requests qr ON q.quote_request_id = qr.id
JOIN services s ON qr.service_id = s.id
WHERE qr.user_id = $1 AND q.status= 'sent'
ORDER BY q.created_at DESC
LIMIT $2 OFFSET $3
`

type GetUserQuotesWithServiceParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

type GetUserQuotesWithServiceRow struct {
	ID             uuid.UUID
	QuoteRequestID uuid.UUID
	Amount         string
	Breakdown      json.RawMessage
	Notes          string
	Status         QuoteStatus
	ExpiresAt      time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
	ServiceName    string
	ServiceIcon    string
	ServiceID      uuid.UUID
}

func (q *Queries) GetUserQuotesWithService(ctx context.Context, arg GetUserQuotesWithServiceParams) ([]GetUserQuotesWithServiceRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserQuotesWithService, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserQuotesWithServiceRow
	for rows.Next() {
		var i GetUserQuotesWithServiceRow
		if err := rows.Scan(
			&i.ID,
			&i.QuoteRequestID,
			&i.Amount,
			&i.Breakdown,
			&i.Notes,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ServiceName,
			&i.ServiceIcon,
			&i.ServiceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQuoteStatus = `-- name: UpdateQuoteStatus :exec
UPDATE quotes SET status = $2, updated_at = NOW() WHERE id = $1
`

type UpdateQuoteStatusParams struct {
	ID     uuid.UUID
	Status QuoteStatus
}

func (q *Queries) UpdateQuoteStatus(ctx context.Context, arg UpdateQuoteStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateQuoteStatus, arg.ID, arg.Status)
	return err
}
