// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: quote_reqs.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const countQuoteRequests = `-- name: CountQuoteRequests :one
SELECT COUNT(*) FROM quote_requests
`

func (q *Queries) CountQuoteRequests(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countQuoteRequests)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserQuoteRequests = `-- name: CountUserQuoteRequests :one
SELECT COUNT(*) FROM quote_requests WHERE user_id=$1
`

func (q *Queries) CountUserQuoteRequests(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserQuoteRequests, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createQuoteRequest = `-- name: CreateQuoteRequest :one
INSERT INTO quote_requests (user_id, service_id, description, attachments)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, service_id, description, attachments, status, created_at, updated_at
`

type CreateQuoteRequestParams struct {
	UserID      uuid.UUID
	ServiceID   uuid.UUID
	Description string
	Attachments []string
}

func (q *Queries) CreateQuoteRequest(ctx context.Context, arg CreateQuoteRequestParams) (QuoteRequest, error) {
	row := q.db.QueryRowContext(ctx, createQuoteRequest,
		arg.UserID,
		arg.ServiceID,
		arg.Description,
		pq.Array(arg.Attachments),
	)
	var i QuoteRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServiceID,
		&i.Description,
		pq.Array(&i.Attachments),
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQuoteRequests = `-- name: GetQuoteRequests :many
SELECT 
    qr.id, qr.user_id, qr.service_id, qr.description, qr.attachments, qr.status, qr.created_at, qr.updated_at, 
    u.email as user_email, 
    u.first_name as user_name,
    s.name as service_name
FROM quote_requests qr
JOIN users u ON qr.user_id = u.id
JOIN services s ON qr.service_id = s.id
ORDER BY qr.created_at DESC
LIMIT $1 OFFSET $2
`

type GetQuoteRequestsParams struct {
	Limit  int32
	Offset int32
}

type GetQuoteRequestsRow struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	ServiceID   uuid.UUID
	Description string
	Attachments []string
	Status      QuoteRequestStatus
	CreatedAt   time.Time
	UpdatedAt   time.Time
	UserEmail   string
	UserName    string
	ServiceName string
}

func (q *Queries) GetQuoteRequests(ctx context.Context, arg GetQuoteRequestsParams) ([]GetQuoteRequestsRow, error) {
	rows, err := q.db.QueryContext(ctx, getQuoteRequests, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetQuoteRequestsRow
	for rows.Next() {
		var i GetQuoteRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ServiceID,
			&i.Description,
			pq.Array(&i.Attachments),
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserEmail,
			&i.UserName,
			&i.ServiceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserQuoteRequests = `-- name: GetUserQuoteRequests :many
SELECT id, user_id, service_id, description, attachments, status, created_at, updated_at FROM quote_requests
WHERE user_id=$1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetUserQuoteRequestsParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) GetUserQuoteRequests(ctx context.Context, arg GetUserQuoteRequestsParams) ([]QuoteRequest, error) {
	rows, err := q.db.QueryContext(ctx, getUserQuoteRequests, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuoteRequest
	for rows.Next() {
		var i QuoteRequest
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ServiceID,
			&i.Description,
			pq.Array(&i.Attachments),
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQuoteRequestStatus = `-- name: UpdateQuoteRequestStatus :exec
UPDATE quote_requests SET status = $2, updated_at = NOW() WHERE id = $1
`

type UpdateQuoteRequestStatusParams struct {
	ID     uuid.UUID
	Status QuoteRequestStatus
}

func (q *Queries) UpdateQuoteRequestStatus(ctx context.Context, arg UpdateQuoteRequestStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateQuoteRequestStatus, arg.ID, arg.Status)
	return err
}
