// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (
user_id, expires_at,
token  )
VALUES ( $1, $2, $3)
RETURNING id, user_id, token, revoked, replaced_by, expires_at, created_at
`

type CreateRefreshTokenParams struct {
	UserID    uuid.UUID
	ExpiresAt time.Time
	Token     string
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, createRefreshToken, arg.UserID, arg.ExpiresAt, arg.Token)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Revoked,
		&i.ReplacedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRefreshToken = `-- name: DeleteRefreshToken :exec
DELETE FROM refresh_tokens
WHERE token=$1
`

func (q *Queries) DeleteRefreshToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteRefreshToken, token)
	return err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, user_id, token, revoked, replaced_by, expires_at, created_at
FROM refresh_tokens
WHERE token = $1
`

func (q *Queries) GetRefreshToken(ctx context.Context, token string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefreshToken, token)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Revoked,
		&i.ReplacedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const refreshTokenExists = `-- name: RefreshTokenExists :one
SELECT EXISTS (
    SELECT 1
    FROM refresh_tokens
    WHERE token = $1
)
`

func (q *Queries) RefreshTokenExists(ctx context.Context, token string) (bool, error) {
	row := q.db.QueryRowContext(ctx, refreshTokenExists, token)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const revokeRefreshTokens = `-- name: RevokeRefreshTokens :exec
UPDATE refresh_tokens
SET 
  revoked=1
WHERE user_id = $1
`

func (q *Queries) RevokeRefreshTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revokeRefreshTokens, userID)
	return err
}

const updateRefreshToken = `-- name: UpdateRefreshToken :exec
UPDATE refresh_tokens
SET 
  token = $1,
  replaced_by = $2,
  revoked=$3
WHERE id = $4
`

type UpdateRefreshTokenParams struct {
	Token      string
	ReplacedBy uuid.NullUUID
	Revoked    bool
	ID         uuid.UUID
}

func (q *Queries) UpdateRefreshToken(ctx context.Context, arg UpdateRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, updateRefreshToken,
		arg.Token,
		arg.ReplacedBy,
		arg.Revoked,
		arg.ID,
	)
	return err
}
