// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: service_category.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createServiceCategory = `-- name: CreateServiceCategory :one
INSERT INTO service_categories (
    slug, name, description, icon
) VALUES (
    $1, $2, $3, $4
) RETURNING id, name, description, slug, created_at, status, icon
`

type CreateServiceCategoryParams struct {
	Slug        string
	Name        string
	Description string
	Icon        string
}

func (q *Queries) CreateServiceCategory(ctx context.Context, arg CreateServiceCategoryParams) (ServiceCategory, error) {
	row := q.db.QueryRowContext(ctx, createServiceCategory,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.Icon,
	)
	var i ServiceCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Slug,
		&i.CreatedAt,
		&i.Status,
		&i.Icon,
	)
	return i, err
}

const getActiveServiceCategories = `-- name: GetActiveServiceCategories :many
SELECT
    sc.id,
    sc.slug,
    sc.name,
    sc.description,
    sc.icon,
    COUNT(s.id)::int AS service_count
FROM service_categories sc
LEFT JOIN services s
    ON s.category_id = sc.id
WHERE sc.status = 'active'
GROUP BY sc.id
ORDER BY sc.created_at DESC
`

type GetActiveServiceCategoriesRow struct {
	ID           uuid.UUID
	Slug         string
	Name         string
	Description  string
	Icon         string
	ServiceCount int32
}

func (q *Queries) GetActiveServiceCategories(ctx context.Context) ([]GetActiveServiceCategoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, getActiveServiceCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveServiceCategoriesRow
	for rows.Next() {
		var i GetActiveServiceCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.ServiceCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServiceCategories = `-- name: GetServiceCategories :many
SELECT
    sc.id,
    sc.slug,
    sc.name,
    sc.description,
    sc.icon,
    COUNT(s.id) AS service_count
FROM service_categories sc
LEFT JOIN services s
    ON s.category_id = sc.id
GROUP BY sc.id
ORDER BY sc.created_at DESC
`

type GetServiceCategoriesRow struct {
	ID           uuid.UUID
	Slug         string
	Name         string
	Description  string
	Icon         string
	ServiceCount int64
}

func (q *Queries) GetServiceCategories(ctx context.Context) ([]GetServiceCategoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, getServiceCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetServiceCategoriesRow
	for rows.Next() {
		var i GetServiceCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.ServiceCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
