// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: service_orders.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const countServiceOrders = `-- name: CountServiceOrders :one
SELECT COUNT(*) FROM service_orders
`

func (q *Queries) CountServiceOrders(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countServiceOrders)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countServiceOrdersByServiceType = `-- name: CountServiceOrdersByServiceType :many
SELECT service_type, COUNT(*) as count FROM service_orders GROUP BY service_type
`

type CountServiceOrdersByServiceTypeRow struct {
	ServiceType string
	Count       int64
}

func (q *Queries) CountServiceOrdersByServiceType(ctx context.Context) ([]CountServiceOrdersByServiceTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, countServiceOrdersByServiceType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountServiceOrdersByServiceTypeRow
	for rows.Next() {
		var i CountServiceOrdersByServiceTypeRow
		if err := rows.Scan(&i.ServiceType, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countServiceOrdersByStatus = `-- name: CountServiceOrdersByStatus :many
SELECT status, COUNT(*) as count FROM service_orders GROUP BY status
`

type CountServiceOrdersByStatusRow struct {
	Status sql.NullString
	Count  int64
}

func (q *Queries) CountServiceOrdersByStatus(ctx context.Context) ([]CountServiceOrdersByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, countServiceOrdersByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountServiceOrdersByStatusRow
	for rows.Next() {
		var i CountServiceOrdersByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createServiceOrder = `-- name: CreateServiceOrder :one
INSERT INTO service_orders (
    order_number, email, full_name, business_name, phone, whatsapp_phone,
    company_size, referral_source, service_type, appliance_details,
    delivery_address, transport_fee, promo_applied, status, user_id, notes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
) RETURNING id, order_number, email, full_name, business_name, phone, whatsapp_phone, company_size, referral_source, service_type, appliance_details, delivery_address, transport_fee, service_fee, promo_applied, status, user_id, notes, created_at, updated_at
`

type CreateServiceOrderParams struct {
	OrderNumber      string
	Email            string
	FullName         string
	BusinessName     string
	Phone            string
	WhatsappPhone    sql.NullString
	CompanySize      string
	ReferralSource   string
	ServiceType      string
	ApplianceDetails pqtype.NullRawMessage
	DeliveryAddress  string
	TransportFee     string
	PromoApplied     sql.NullBool
	Status           sql.NullString
	UserID           uuid.NullUUID
	Notes            sql.NullString
}

func (q *Queries) CreateServiceOrder(ctx context.Context, arg CreateServiceOrderParams) (ServiceOrder, error) {
	row := q.db.QueryRowContext(ctx, createServiceOrder,
		arg.OrderNumber,
		arg.Email,
		arg.FullName,
		arg.BusinessName,
		arg.Phone,
		arg.WhatsappPhone,
		arg.CompanySize,
		arg.ReferralSource,
		arg.ServiceType,
		arg.ApplianceDetails,
		arg.DeliveryAddress,
		arg.TransportFee,
		arg.PromoApplied,
		arg.Status,
		arg.UserID,
		arg.Notes,
	)
	var i ServiceOrder
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.Email,
		&i.FullName,
		&i.BusinessName,
		&i.Phone,
		&i.WhatsappPhone,
		&i.CompanySize,
		&i.ReferralSource,
		&i.ServiceType,
		&i.ApplianceDetails,
		&i.DeliveryAddress,
		&i.TransportFee,
		&i.ServiceFee,
		&i.PromoApplied,
		&i.Status,
		&i.UserID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServiceOrderByID = `-- name: GetServiceOrderByID :one
SELECT id, order_number, email, full_name, business_name, phone, whatsapp_phone, company_size, referral_source, service_type, appliance_details, delivery_address, transport_fee, service_fee, promo_applied, status, user_id, notes, created_at, updated_at FROM service_orders WHERE id = $1
`

func (q *Queries) GetServiceOrderByID(ctx context.Context, id uuid.UUID) (ServiceOrder, error) {
	row := q.db.QueryRowContext(ctx, getServiceOrderByID, id)
	var i ServiceOrder
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.Email,
		&i.FullName,
		&i.BusinessName,
		&i.Phone,
		&i.WhatsappPhone,
		&i.CompanySize,
		&i.ReferralSource,
		&i.ServiceType,
		&i.ApplianceDetails,
		&i.DeliveryAddress,
		&i.TransportFee,
		&i.ServiceFee,
		&i.PromoApplied,
		&i.Status,
		&i.UserID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServiceOrderByNumber = `-- name: GetServiceOrderByNumber :one
SELECT id, order_number, email, full_name, business_name, phone, whatsapp_phone, company_size, referral_source, service_type, appliance_details, delivery_address, transport_fee, service_fee, promo_applied, status, user_id, notes, created_at, updated_at FROM service_orders WHERE order_number = $1
`

func (q *Queries) GetServiceOrderByNumber(ctx context.Context, orderNumber string) (ServiceOrder, error) {
	row := q.db.QueryRowContext(ctx, getServiceOrderByNumber, orderNumber)
	var i ServiceOrder
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.Email,
		&i.FullName,
		&i.BusinessName,
		&i.Phone,
		&i.WhatsappPhone,
		&i.CompanySize,
		&i.ReferralSource,
		&i.ServiceType,
		&i.ApplianceDetails,
		&i.DeliveryAddress,
		&i.TransportFee,
		&i.ServiceFee,
		&i.PromoApplied,
		&i.Status,
		&i.UserID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServiceOrdersByEmail = `-- name: GetServiceOrdersByEmail :many
SELECT id, order_number, email, full_name, business_name, phone, whatsapp_phone, company_size, referral_source, service_type, appliance_details, delivery_address, transport_fee, service_fee, promo_applied, status, user_id, notes, created_at, updated_at FROM service_orders WHERE email = $1 ORDER BY created_at DESC
`

func (q *Queries) GetServiceOrdersByEmail(ctx context.Context, email string) ([]ServiceOrder, error) {
	rows, err := q.db.QueryContext(ctx, getServiceOrdersByEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceOrder
	for rows.Next() {
		var i ServiceOrder
		if err := rows.Scan(
			&i.ID,
			&i.OrderNumber,
			&i.Email,
			&i.FullName,
			&i.BusinessName,
			&i.Phone,
			&i.WhatsappPhone,
			&i.CompanySize,
			&i.ReferralSource,
			&i.ServiceType,
			&i.ApplianceDetails,
			&i.DeliveryAddress,
			&i.TransportFee,
			&i.ServiceFee,
			&i.PromoApplied,
			&i.Status,
			&i.UserID,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServiceOrdersByUserID = `-- name: GetServiceOrdersByUserID :many
SELECT id, order_number, email, full_name, business_name, phone, whatsapp_phone, company_size, referral_source, service_type, appliance_details, delivery_address, transport_fee, service_fee, promo_applied, status, user_id, notes, created_at, updated_at FROM service_orders WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetServiceOrdersByUserID(ctx context.Context, userID uuid.NullUUID) ([]ServiceOrder, error) {
	rows, err := q.db.QueryContext(ctx, getServiceOrdersByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceOrder
	for rows.Next() {
		var i ServiceOrder
		if err := rows.Scan(
			&i.ID,
			&i.OrderNumber,
			&i.Email,
			&i.FullName,
			&i.BusinessName,
			&i.Phone,
			&i.WhatsappPhone,
			&i.CompanySize,
			&i.ReferralSource,
			&i.ServiceType,
			&i.ApplianceDetails,
			&i.DeliveryAddress,
			&i.TransportFee,
			&i.ServiceFee,
			&i.PromoApplied,
			&i.Status,
			&i.UserID,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceOrders = `-- name: ListServiceOrders :many
SELECT id, order_number, email, full_name, business_name, phone, whatsapp_phone, company_size, referral_source, service_type, appliance_details, delivery_address, transport_fee, service_fee, promo_applied, status, user_id, notes, created_at, updated_at FROM service_orders
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListServiceOrdersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListServiceOrders(ctx context.Context, arg ListServiceOrdersParams) ([]ServiceOrder, error) {
	rows, err := q.db.QueryContext(ctx, listServiceOrders, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceOrder
	for rows.Next() {
		var i ServiceOrder
		if err := rows.Scan(
			&i.ID,
			&i.OrderNumber,
			&i.Email,
			&i.FullName,
			&i.BusinessName,
			&i.Phone,
			&i.WhatsappPhone,
			&i.CompanySize,
			&i.ReferralSource,
			&i.ServiceType,
			&i.ApplianceDetails,
			&i.DeliveryAddress,
			&i.TransportFee,
			&i.ServiceFee,
			&i.PromoApplied,
			&i.Status,
			&i.UserID,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateServiceOrderStatus = `-- name: UpdateServiceOrderStatus :one
UPDATE service_orders
SET status = $2, updated_at = NOW()
WHERE id = $1 RETURNING id, order_number, email, full_name, business_name, phone, whatsapp_phone, company_size, referral_source, service_type, appliance_details, delivery_address, transport_fee, service_fee, promo_applied, status, user_id, notes, created_at, updated_at
`

type UpdateServiceOrderStatusParams struct {
	ID     uuid.UUID
	Status sql.NullString
}

func (q *Queries) UpdateServiceOrderStatus(ctx context.Context, arg UpdateServiceOrderStatusParams) (ServiceOrder, error) {
	row := q.db.QueryRowContext(ctx, updateServiceOrderStatus, arg.ID, arg.Status)
	var i ServiceOrder
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.Email,
		&i.FullName,
		&i.BusinessName,
		&i.Phone,
		&i.WhatsappPhone,
		&i.CompanySize,
		&i.ReferralSource,
		&i.ServiceType,
		&i.ApplianceDetails,
		&i.DeliveryAddress,
		&i.TransportFee,
		&i.ServiceFee,
		&i.PromoApplied,
		&i.Status,
		&i.UserID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
