// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: services.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const countActiveServices = `-- name: CountActiveServices :one
SELECT COUNT(*) FROM services WHERE is_active = true
`

func (q *Queries) CountActiveServices(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveServices)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countServices = `-- name: CountServices :one
SELECT COUNT(*) FROM services
`

func (q *Queries) CountServices(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countServices)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createService = `-- name: CreateService :one
INSERT INTO services (
    name, description, is_featured , tags , image, min_price, category_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, name, description, is_active, is_featured, image, tags, created_at, min_price, category_id
`

type CreateServiceParams struct {
	Name        string
	Description string
	IsFeatured  bool
	Tags        []string
	Image       string
	MinPrice    string
	CategoryID  uuid.NullUUID
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRowContext(ctx, createService,
		arg.Name,
		arg.Description,
		arg.IsFeatured,
		pq.Array(arg.Tags),
		arg.Image,
		arg.MinPrice,
		arg.CategoryID,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.IsFeatured,
		&i.Image,
		pq.Array(&i.Tags),
		&i.CreatedAt,
		&i.MinPrice,
		&i.CategoryID,
	)
	return i, err
}

const getActiveServices = `-- name: GetActiveServices :many
SELECT id, name, description, is_active, is_featured, image, tags, created_at, min_price, category_id FROM services 
WHERE is_active = true
ORDER BY 
    is_featured DESC, 
    created_at DESC
LIMIT $1 OFFSET $2
`

type GetActiveServicesParams struct {
	Limit  int32
	Offset int32
}

// Used for the landing page
func (q *Queries) GetActiveServices(ctx context.Context, arg GetActiveServicesParams) ([]Service, error) {
	rows, err := q.db.QueryContext(ctx, getActiveServices, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.IsFeatured,
			&i.Image,
			pq.Array(&i.Tags),
			&i.CreatedAt,
			&i.MinPrice,
			&i.CategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getService = `-- name: GetService :one
SELECT id, name, description, is_active, is_featured, image, tags, created_at, min_price, category_id FROM services WHERE id = $1
`

func (q *Queries) GetService(ctx context.Context, id uuid.UUID) (Service, error) {
	row := q.db.QueryRowContext(ctx, getService, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.IsFeatured,
		&i.Image,
		pq.Array(&i.Tags),
		&i.CreatedAt,
		&i.MinPrice,
		&i.CategoryID,
	)
	return i, err
}

const getServiceByName = `-- name: GetServiceByName :one
SELECT id, name, description, is_active, is_featured, image, tags, created_at, min_price, category_id FROM services WHERE name = $1
`

func (q *Queries) GetServiceByName(ctx context.Context, name string) (Service, error) {
	row := q.db.QueryRowContext(ctx, getServiceByName, name)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.IsFeatured,
		&i.Image,
		pq.Array(&i.Tags),
		&i.CreatedAt,
		&i.MinPrice,
		&i.CategoryID,
	)
	return i, err
}

const getServices = `-- name: GetServices :many
SELECT id, name, description, is_active, is_featured, image, tags, created_at, min_price, category_id FROM services 
ORDER BY 
    is_featured DESC, 
    created_at DESC
LIMIT $1 OFFSET $2
`

type GetServicesParams struct {
	Limit  int32
	Offset int32
}

// Used for the admin dashboard (shows everything)
func (q *Queries) GetServices(ctx context.Context, arg GetServicesParams) ([]Service, error) {
	rows, err := q.db.QueryContext(ctx, getServices, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.IsFeatured,
			&i.Image,
			pq.Array(&i.Tags),
			&i.CreatedAt,
			&i.MinPrice,
			&i.CategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateServiceStatus = `-- name: UpdateServiceStatus :exec
UPDATE services SET is_active = $2 WHERE id = $1
`

type UpdateServiceStatusParams struct {
	ID       uuid.UUID
	IsActive bool
}

func (q *Queries) UpdateServiceStatus(ctx context.Context, arg UpdateServiceStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateServiceStatus, arg.ID, arg.IsActive)
	return err
}
