// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email, password_hash, first_name, last_name, phone_number, address, role, country, state, is_email_verified, google_id, avatar_url
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,$8,$9,$10,$11,$12
) RETURNING id, email, password_hash, first_name, last_name, phone_number, address, country, state, role, created_at, updated_at, is_email_verified, google_id, avatar_url
`

type CreateUserParams struct {
	Email           string
	PasswordHash    sql.NullString
	FirstName       string
	LastName        string
	PhoneNumber     sql.NullString
	Address         sql.NullString
	Role            string
	Country         sql.NullString
	State           sql.NullString
	IsEmailVerified sql.NullBool
	GoogleID        sql.NullString
	AvatarUrl       sql.NullString
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.FirstName,
		arg.LastName,
		arg.PhoneNumber,
		arg.Address,
		arg.Role,
		arg.Country,
		arg.State,
		arg.IsEmailVerified,
		arg.GoogleID,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.PhoneNumber,
		&i.Address,
		&i.Country,
		&i.State,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsEmailVerified,
		&i.GoogleID,
		&i.AvatarUrl,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, first_name, last_name, phone_number, address, country, state, role, created_at, updated_at, is_email_verified, google_id, avatar_url FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.PhoneNumber,
		&i.Address,
		&i.Country,
		&i.State,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsEmailVerified,
		&i.GoogleID,
		&i.AvatarUrl,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, first_name, last_name, phone_number, address, country, state, role, created_at, updated_at, is_email_verified, google_id, avatar_url FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.PhoneNumber,
		&i.Address,
		&i.Country,
		&i.State,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsEmailVerified,
		&i.GoogleID,
		&i.AvatarUrl,
	)
	return i, err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users
SET 
  password_hash = $1
WHERE email = $2
`

type UpdatePasswordParams struct {
	PasswordHash sql.NullString
	Email        string
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.ExecContext(ctx, updatePassword, arg.PasswordHash, arg.Email)
	return err
}

const updateUserForOAuth = `-- name: UpdateUserForOAuth :exec
UPDATE users
SET
    google_id = $2,
    is_email_verified = $3,
    avatar_url = $4
WHERE id = $1
`

type UpdateUserForOAuthParams struct {
	ID              uuid.UUID
	GoogleID        sql.NullString
	IsEmailVerified sql.NullBool
	AvatarUrl       sql.NullString
}

func (q *Queries) UpdateUserForOAuth(ctx context.Context, arg UpdateUserForOAuthParams) error {
	_, err := q.db.ExecContext(ctx, updateUserForOAuth,
		arg.ID,
		arg.GoogleID,
		arg.IsEmailVerified,
		arg.AvatarUrl,
	)
	return err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users SET
    role = $2,
    updated_at = NOW()
WHERE id = $1 RETURNING id, email, password_hash, first_name, last_name, phone_number, address, country, state, role, created_at, updated_at, is_email_verified, google_id, avatar_url
`

type UpdateUserRoleParams struct {
	ID   uuid.UUID
	Role string
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserRole, arg.ID, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.PhoneNumber,
		&i.Address,
		&i.Country,
		&i.State,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsEmailVerified,
		&i.GoogleID,
		&i.AvatarUrl,
	)
	return i, err
}

const userExists = `-- name: UserExists :one
SELECT EXISTS (
    SELECT 1
    FROM users
    WHERE email = $1
)
`

func (q *Queries) UserExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRowContext(ctx, userExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
