name: Build and Deploy

on:
  push:
    branches:
      - main  

env:
  PROJECT_ID: 'n3xtbridge' 
  REGION: 'us-east1'               
  SERVICE: 'n3xtbridge-backend'          

permissions:
  contents: read
  id-token: write 

jobs:
  build:
    name: Build and push Docker images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4

      - name: Build the server binary
        run: |
          chmod +x ./build.sh
          ./build.sh

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        run: |
          DEPLOY_VERSION=$(git rev-parse --short HEAD)
          docker build . -t muhammadolammi/n3xtbridge-backend:latest -t muhammadolammi/n3xtbridge-backend:${DEPLOY_VERSION}
          docker push muhammadolammi/n3xtbridge-backend --all-tags

  deploy:
    needs: build
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'

      - name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: '${{ env.SERVICE }}'
          region: '${{ env.REGION }}'
          project_id: '${{ env.PROJECT_ID }}'
          image: 'index.docker.io/muhammadolammi/n3xtbridge-backend:latest'
          flags: '--allow-unauthenticated'
          env_vars: |
            ENV=${{ secrets.ENV }}
            DB_URL=${{ secrets.DB_URL }}
            JWT_KEY=${{ secrets.JWT_KEY }}
            CLIENT_API_KEY=${{ secrets.CLIENT_API_KEY }}
            PAYSTACK_SECRET_KEY=${{ secrets.PAYSTACK_SECRET_KEY }}

            SMTP_SERVER=${{ secrets.SMTP_SERVER }}
            SMTP_PORT=${{ secrets.SMTP_PORT }}
            SMTP_USERNAME=${{ secrets.SMTP_USERNAME }}
            SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}

            R2_ACCOUNT_ID=${{ secrets.R2_ACCOUNT_ID }}
            R2_BUCKET=${{ secrets.R2_BUCKET }}
            R2_BUCKET_PUB=${{ secrets.R2_BUCKET_PUB }}
            R2_SECRET_KEY=${{ secrets.R2_SECRET_KEY }}
            R2_ACCESS_KEY=${{ secrets.R2_ACCESS_KEY }}
            REDIS_URL=${{ secrets.REDIS_URL }}